server:
  port: 3000
spring:
  boot:
  application:
    name: PAYMENT-SERVICE

  datasource:
    driverClasName: org.h2.Driver
    url: jdbc:h2:file:./database/patient_db
    username: root
    password:
  h2:
    console:
      enable: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka